version: '3.8'

services:
  db:
    image: postgres:15
    container_name: rimovies-db
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - rimovies_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: rimovies-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  rimovies_pgdata:
  redis_data:
