version: '3.9'

services:
  db:
    image: postgres:15
    container_name: rimovies-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - rimovies_pgdata:/var/lib/postgresql/data

volumes:
  rimovies_pgdata:
